/**
 * Builds the Rolefit brand files from components/brand/geometry.ts:
 *   public/brand/*.svg, favicon + touch icon + social card PNGs, and
 *   components/brand/wordmark.generated.ts (the wordmark as outlined paths).
 *
 * Run: npx tsx scripts/brand/build-brand-assets.ts
 * Needs the dev dependencies opentype.js, geist (font source) and sharp.
 */
import fs from 'node:fs'
import path from 'node:path'
import opentype from 'opentype.js'
import sharp from 'sharp'
import { BRAND_COLORS, MARK, MARK_SIZE, WORDMARK_TEXT } from '../../components/brand/geometry'

const root = path.resolve(__dirname, '../..')
const fontDir = path.join(root, 'node_modules/geist/dist/fonts/geist-sans')

function loadFont(file: string) {
  const buf = fs.readFileSync(path.join(fontDir, file))
  return opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
}

type Palette = (typeof BRAND_COLORS)['light'] | (typeof BRAND_COLORS)['dark']

/** SVG markup for the mark. `id` keeps mask ids unique when several marks share a document. */
function markElements(p: { main: string; badge: string; fold: string }, id: string, transform = '') {
  const c = MARK.cutouts
  const b = MARK.badge
  return `<g${transform ? ` transform="${transform}"` : ''}>
    <defs>
      <mask id="${id}-doc" maskUnits="userSpaceOnUse" x="0" y="0" width="${MARK_SIZE}" height="${MARK_SIZE}">
        <rect width="${MARK_SIZE}" height="${MARK_SIZE}" fill="#fff"/>
        ${c.lines.map((l) => `<rect x="${l.x}" y="${l.y}" width="${l.w}" height="${l.h}" rx="${l.h / 2}" fill="#000"/>`).join('')}
        <circle cx="${c.head.cx}" cy="${c.head.cy}" r="${c.head.r}" fill="#000"/>
        <path d="${c.shoulders}" fill="#000"/>
        <circle cx="${b.cx}" cy="${b.cy}" r="${MARK.badgeGap}" fill="#000"/>
      </mask>
      <mask id="${id}-badge" maskUnits="userSpaceOnUse" x="0" y="0" width="${MARK_SIZE}" height="${MARK_SIZE}">
        <rect width="${MARK_SIZE}" height="${MARK_SIZE}" fill="#fff"/>
        <path d="${MARK.check}" fill="none" stroke="#000" stroke-width="${MARK.checkWidth}" stroke-linecap="round" stroke-linejoin="round"/>
      </mask>
    </defs>
    <path d="${MARK.doc}" fill="${p.main}" mask="url(#${id}-doc)"/>
    <path d="${MARK.fold}" fill="${p.fold}"/>
    <circle cx="${b.cx}" cy="${b.cy}" r="${b.r}" fill="${p.badge}" mask="url(#${id}-badge)"/>
  </g>`
}

// ---- wordmark: outlined from Geist SemiBold -------------------------------------------------
const semibold = loadFont('Geist-SemiBold.ttf')
const regular = loadFont('Geist-Regular.ttf')

const WORD_SIZE = 38
const WORD_X = MARK_SIZE + 14
const capHeight = (semibold.tables.os2.sCapHeight / semibold.unitsPerEm) * WORD_SIZE
const baseline = MARK_SIZE / 2 + capHeight / 2
const wordPath = semibold.getPath(WORDMARK_TEXT, WORD_X, baseline, WORD_SIZE, { letterSpacing: -0.025 })
const wb = wordPath.getBoundingBox()
const wordD = wordPath.toPathData(2)
const LOCKUP_W = Math.ceil(wb.x2 + 2)

fs.writeFileSync(
  path.join(root, 'components/brand/wordmark.generated.ts'),
  `// Generated by scripts/brand/build-brand-assets.ts. Do not edit by hand.
export const WORDMARK_PATH = '${wordD}'
export const LOCKUP_WIDTH = ${LOCKUP_W}
export const LOCKUP_HEIGHT = ${MARK_SIZE}
`
)

const svgOpen = (w: number, h: number) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="Rolefit">`

function lockup(p: Palette, id: string) {
  return `${svgOpen(LOCKUP_W, MARK_SIZE)}
  <title>Rolefit</title>
  ${markElements(p, id)}
  <path d="${wordD}" fill="${p.ink}"/>
</svg>
`
}

function markOnly(p: Palette, id: string) {
  return `${svgOpen(MARK_SIZE, MARK_SIZE)}
  <title>Rolefit</title>
  ${markElements(p, id)}
</svg>
`
}

/** App tile: white mark on the brand blue (favicon / touch icon). */
function tile(size: number, radius: number) {
  const pad = size * 0.2
  const scale = (size - pad * 2) / MARK_SIZE
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
  <rect width="${size}" height="${size}" rx="${radius}" fill="${BRAND_COLORS.light.main}"/>
  ${markElements({ main: '#ffffff', badge: '#dde7ff', fold: '#94b0ff' }, 'tile', `translate(${pad} ${pad}) scale(${scale})`)}
</svg>
`
}

const out = (...p: string[]) => path.join(root, ...p)
fs.mkdirSync(out('public/brand'), { recursive: true })
fs.writeFileSync(out('public/brand/rolefit-mark.svg'), markOnly(BRAND_COLORS.light, 'm'))
fs.writeFileSync(out('public/brand/rolefit-mark-dark.svg'), markOnly(BRAND_COLORS.dark, 'm'))
fs.writeFileSync(out('public/brand/rolefit-logo.svg'), lockup(BRAND_COLORS.light, 'l'))
fs.writeFileSync(out('public/brand/rolefit-logo-dark.svg'), lockup(BRAND_COLORS.dark, 'l'))
fs.writeFileSync(out('public/brand/icon.svg'), tile(64, 14))

// ---- raster exports ---------------------------------------------------------------------------
async function png(svg: string, size: number, file: string) {
  await sharp(Buffer.from(svg), { density: 384 }).resize(size, size).png().toFile(out(file))
}

/** ICO container holding a single PNG image (valid since Windows Vista, supported by all browsers). */
function icoFromPng(pngBuf: Buffer, size: number) {
  const header = Buffer.alloc(22)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(1, 4)
  header.writeUInt8(size >= 256 ? 0 : size, 6)
  header.writeUInt8(size >= 256 ? 0 : size, 7)
  header.writeUInt16LE(1, 10)
  header.writeUInt16LE(32, 12)
  header.writeUInt32LE(pngBuf.length, 14)
  header.writeUInt32LE(22, 18)
  return Buffer.concat([header, pngBuf])
}

async function main() {
  await png(tile(512, 112), 64, 'public/favicon.png')
  await png(tile(512, 0), 180, 'public/apple-touch-icon.png') // iOS applies its own corner mask
  const ico32 = await sharp(Buffer.from(tile(512, 112)), { density: 384 }).resize(32, 32).png().toBuffer()
  fs.writeFileSync(out('public/favicon.ico'), icoFromPng(ico32, 32))

  // Social card, 1200x630: lockup at left, tagline below. Text is outlined, so no font is needed to render it.
  const W = 1200
  const H = 630
  const lockScale = 2.6
  const lw = LOCKUP_W * lockScale
  const lx = 96
  const ly = 150
  const tag1 = regular.getPath('Tailor your resume to any role.', lx, 400, 54, { letterSpacing: -0.02 }).toPathData(2)
  const tag2 = regular.getPath('Nothing invented.', lx, 470, 54, { letterSpacing: -0.02 }).toPathData(2)
  const p = BRAND_COLORS.light
  const og = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <rect width="${W}" height="${H}" fill="${p.bg}"/>
  <rect x="${lx}" y="${H - 96}" width="${W - lx * 2}" height="2" fill="#e1e5ea"/>
  <g transform="translate(${lx} ${ly}) scale(${lockScale})">
    ${markElements(p, 'og')}
    <path d="${wordD}" fill="${p.ink}"/>
  </g>
  <path d="${tag1}" fill="${p.ink}"/>
  <path d="${tag2}" fill="${p.main}"/>
</svg>`
  void lw
  await sharp(Buffer.from(og), { density: 192 }).resize(W, H).png().toFile(out('public/brand/og.png'))
  console.log('Brand assets written. Lockup width', LOCKUP_W)
}

main()
